name: Package

on:
  - workflow_call
  - workflow_dispatch

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Move existing output directories
        uses: addnab/docker-run-action@v3
        with:
          image: fackop/ppdocker
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: mkdir -p out-cmake out-cpack && mv out-cmake .out-cmake && mv out-cpack .out-cpack
      - name: CMake
        uses: addnab/docker-run-action@v3
        with:
          image: fackop/ppdocker
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: cmake -S . -B out-cmake/ -G "Ninja Multi-Config"
      - name: CPack
        uses: addnab/docker-run-action@v3
        with:
          image: fackop/ppdocker
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: cpack --config out-cmake/CPackConfig.cmake -B out-cpack/
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: out-cpack/PPstyle-*.*.*-*.tar.gz
      - name: Move output directories back
        uses: addnab/docker-run-action@v3
        with:
          image: fackop/ppdocker
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: rm -r out-cmake/ out-cpack/; mv .out-cmake out-cmake && mv .out-cpack out-cpack
