name: Package

on:
  - workflow_call
  - workflow_dispatch

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: CMake
        uses: Petkr/PPactions/cmake-generate@latest
        with:
          source_dir: .
          output_dir: out-cmake
          generator: Ninja Multi-Config
      - name: CPack
        uses: Petkr/PPactions/cpack@latest
        with:
          config_dir: out-cmake
          output_dir: out-cpack
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: out-cpack/*.tar.gz
