name: Release

on: 
  push:
    tags:
      - '*'

jobs:
  package:
    runs-on: ubuntu-latest
    uses: Petkr/PPstyle/.github/workflows/package.yml@main
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create package
        uses: 
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out-cpack/PPstyle-*.*.*-*.tar.gz
